[fmt]
line_length = 120
tab_width = 2
bracket_spacing = false
int_types = 'long'
quote_style = 'single'
number_underscore = 'thousands'
multiline_func_header = 'params_first'

[profile.default]
solc = '0.8.19'
evm_version = 'paris'   
src = 'solidity'
test = 'solidity/test'
out = 'out'
libs = ['lib']
fuzz_runs = 1000
optimizer_runs = 10_000
ffi = true
build_info = true
extra_output = ['storageLayout', 'evm.gasEstimates']
fs_permissions = [{ access = "read", path = "./"}]

[profile.optimized]
via_ir = true
out = 'out-via-ir'
fuzz_runs = 5000

[profile.test]
via_ir = true
out = 'out-via-ir'
fuzz_runs = 5000
src = 'solidity/test'

[rpc_endpoints]
ethereum_mainnet="https://eth-mainnet.g.alchemy.com/v2/${ALCHEMY_KEY}"
optimism="https://opt-mainnet.g.alchemy.com/v2/${ALCHEMY_KEY}"
polygon="https://polygon-mainnet.g.alchemy.com/v2/${ALCHEMY_KEY}"
arbitrum="https://arb-mainnet.g.alchemy.com/v2/${ALCHEMY_KEY}"
bnb="${BNB_MAINNET_RPC}"
gnosis="${GNOSIS_MAINNET_RPC}"
ethereum_goerli="https://eth-goerli.g.alchemy.com/v2/${ALCHEMY_KEY}"
optimism_goerli="https://opt-goerli.g.alchemy.com/v2/${ALCHEMY_KEY}"
polygon_mumbai="https://polygon-mumbai.g.alchemy.com/v2/${ALCHEMY_KEY}"
arbitrum_goerli="https://arb-goerli.g.alchemy.com/v2/${ALCHEMY_KEY}"
bnb_testnet="${BNB_TESTNET_RPC}"
gnosis_chiado="${GNOSIS_CHIADO_RPC}"
anvil = "http://127.0.0.1:8545"