name: Sphinx Propose

# Triggers a deployment when a change is merged to main
on:
  push:
    branches:
      - main
      - dev

jobs:
  sphinx-propose:
    runs-on: ubuntu-latest
    if: github.repository == 'defi-wonderland/zodiac-connext-module-factory'

    env:
      DEPLOYMENT_TARGET: ${{ (github.ref == 'refs/heads/main' && 'mainnets') || (github.ref == 'refs/heads/dev' && 'testnets') }}
      PROPOSER_PRIVATE_KEY: ${{ secrets.PROPOSER_PRIVATE_KEY }}
      SPHINX_API_KEY: ${{ secrets.SPHINX_API_KEY }}
      ALCHEMY_KEY: ${{ secrets.ALCHEMY_KEY }}
      BNB_MAINNET_RPC: ${{ secrets.BNB_MAINNET_RPC }}
      GNOSIS_MAINNET_RPC: ${{ secrets.GNOSIS_MAINNET_RPC }}
      BNB_TESTNET_RPC: ${{ secrets.BNB_TESTNET_RPC }}
      GNOSIS_CHIADO_RPC: ${{ secrets.GNOSIS_CHIADO_RPC }}

    steps:
      - uses: actions/checkout@v3

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Install Dependencies
        run: yarn --frozen-lockfile
        
      - name: Propose
        run: npx sphinx propose --config ./sphinx/deploy.config.ts --confirm --$DEPLOYMENT_TARGET
        
      - name: Propose
        run: npx sphinx propose --config ./sphinx/deploy-optimism.config.ts --confirm --$DEPLOYMENT_TARGET